name: .NET
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - # チェックアウトアクションを記入してください
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.412
    - name: Restore dependencies
      # この行にBuildステップに対応する形でdotnetのリストアコマンドを記入してください
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish ../../src/SampleApplication.csproj -c Release -o ${{env.DOTNET_ROOT}}/webapp
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
         name: dotnet-webapp
        path: ../../src/SampleApplication.csproj　#ビルド成果物のパスを記入してください
